FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY ui/package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application (excluding node_modules)
COPY ui/src /app/src
COPY ui/public /app/public
COPY ui/index.html /app/index.html
COPY ui/vite.config.js /app/vite.config.js

# Expose the port
EXPOSE 3000

# Command to run the application
#CMD ["npm", "start"]