version: '1.0'
flow:
  id: testr2
  description: this is test 2
  tasks:
  - id: 7
    type: s3_list
    name: delete1
    description: delete1
    config:
      bucket: 's3-tst'
    sequence: 1
  - id: 8
    type: s3_list
    name: list1
    description: list1
    config:
      bucket: 's3-test'
    sequence: 1
  - id: 9
    type: bash
    name: bash1
    description: bash1
    config:
      bash_command: 'echo test'
    sequence: 1
  dependencies:
  - from: 7
    to: 8
    type: success
    condition: null
  - from: 8
    to: 9
    type: success
    condition: null
metadata:
  created_at: '2025-04-20T00:42:23.759480'
  updated_at: '2025-04-20T00:42:23.759480'
  version: '1.0'
  engine: airflow
