version: '1.0'
flow:
  id: test1
  description: First test flow.
  tasks:
  - id: 74
    type: s3_copy
    name: New S3CopyOperatorFactory
    description: New S3CopyOperatorFactory
    config:
      verify: true
      aws_conn_id: aws_default
      dest_bucket_key: test
      dest_bucket_name: test
      source_bucket_key: test
      source_bucket_name: test
    sequence: 1
  - id: 75
    type: s3_list
    name: New S3ListOperatorFactory
    description: New S3ListOperatorFactory
    config:
      verify: true
      aws_conn_id: aws_default
      bucket: test
    sequence: 1
  - id: 76
    type: s3_copy
    name: New S3CopyOperatorFactory
    description: New S3CopyOperatorFactory
    config:
      verify: true
      aws_conn_id: aws_default
      dest_bucket_key: test
      dest_bucket_name: test
      source_bucket_key: test
      source_bucket_name: test
    sequence: 2
  dependencies:
  - from: 74
    to: 75
    type: success
    condition: null
  - from: 75
    to: 76
    type: success
    condition: null
metadata:
  created_at: '2025-05-07T18:48:36.647420'
  updated_at: '2025-05-07T18:48:36.647420'
  version: '1.0'
  engine: airflow
